import {
  EXECUTION_STORAGE_VERSION,
  type ExecutionState,
  type ExecutionTask,
  type ExtractedTaskCandidate,
  type SourceDocument,
  type TaskCategory,
  type TaskImpact,
  type TaskPriority,
  type TaskStatus,
  type TaskUrgency,
  type Workstream,
} from './types';

const FOUNDER_OWNER = 'Founder';

export const APPROVED_SEEDED_SOURCE_DOCUMENT_NAMES = [
  'Conference Proposal.md',
  'hoodie-llm-product-context.md',
  'Public Sector Outreach for Hoodie.md',
  'Product Opportunity Study for Hoodie.md',
  'Organic GTM for Hoodie.md',
  'LinkedIn for Hoodie.md',
] as const;

const APPROVED_SEEDED_SOURCE_DOCUMENT_SET = new Set<string>(APPROVED_SEEDED_SOURCE_DOCUMENT_NAMES);

export function isApprovedSeedSourceDocumentName(name: string) {
  return APPROVED_SEEDED_SOURCE_DOCUMENT_SET.has(name);
}

function isoNow(now: Date) {
  return now.toISOString();
}

export function toISODate(date: Date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function addDays(base: Date, days: number) {
  const next = new Date(base);
  next.setDate(next.getDate() + days);
  return next;
}

function dateFromDay(base: Date, day?: number) {
  if (!day) return undefined;
  return toISODate(addDays(base, day - 1));
}

function sourceDocuments(now: Date): SourceDocument[] {
  const importedAt = isoNow(now);

  return [
    {
      id: 'doc-conference-proposal',
      name: 'Conference Proposal.md',
      path: '/Users/rushi/Downloads/Conference Proposal.md',
      type: 'uploaded-markdown',
      imported_at: importedAt,
      last_reviewed_at: importedAt,
      sections: [
        {
          id: 'conference-first-actions',
          title: 'First 10 actions to start now',
          line_start: 493,
          excerpt: 'Confirm approval pathway, lock working title, finalise approved wording rules, build invite list, identify speakers, draft landing page and registration form.',
          workstreams: [
            'Indian Student Transition and Wellbeing Forum',
            'Conference partner/sponsor/resource outreach',
            'University and admissions outreach',
          ],
        },
        {
          id: 'conference-ops-plan',
          title: 'Event operations plan',
          line_start: 268,
          excerpt: 'Registration flow, landing page structure, speaker management, reminder sequence, accessibility, recording, and post-event follow-up.',
          workstreams: [
            'Indian Student Transition and Wellbeing Forum',
            'Conference partner/sponsor/resource outreach',
          ],
        },
        {
          id: 'conference-hci-proposal',
          title: 'Role requested from the High Commission',
          line_start: 628,
          excerpt: 'Seek approval in principle, approved wording, opening remarks, invite support, liaison nomination, and language review before publication.',
          workstreams: ['Indian Student Transition and Wellbeing Forum'],
        },
        {
          id: 'conference-resource-pack',
          title: 'Draft resource pack outline',
          line_start: 901,
          excerpt: 'Conference summary, slide deck, pre-arrival checklist, housing readiness guide, official links, OSHC sheet, referral map, and optional Hoodie pilot explainer.',
          workstreams: [
            'Conference partner/sponsor/resource outreach',
            'Admin, proof assets, CRM, reporting, and follow-ups',
          ],
        },
      ],
    },
    {
      id: 'doc-product-context',
      name: 'hoodie-llm-product-context.md',
      path: '/Users/rushi/Downloads/hoodie-llm-product-context.md',
      type: 'uploaded-markdown',
      imported_at: importedAt,
      last_reviewed_at: importedAt,
      sections: [
        {
          id: 'product-quick-facts',
          title: 'Quick Facts',
          line_start: 10,
          excerpt: 'Hoodie is an Australia newcomer support, rental safety, suburb context, and evidence capture app. Several public URLs and direct iOS listing details remain to be filled in.',
          workstreams: [
            'ASO / app store optimisation',
            'Website / landing pages / analytics setup',
            'Admin, proof assets, CRM, reporting, and follow-ups',
          ],
        },
        {
          id: 'product-key-features',
          title: 'Key Features, Benefits, Use Cases, and Outcomes',
          line_start: 150,
          excerpt: 'Arrival Hub, Hood Map, reporting, Evidence Vault, Rental Timeline, Legal Prep, Application Kit, Scam Checker, Vibe, Household tools, Notifications and Public Plans.',
          workstreams: [
            'Product roadmap and feature research',
            'UX simplification / Codex product tasks',
            'Investor and pitch deck',
          ],
        },
        {
          id: 'product-workflows',
          title: 'Practical Workflows',
          line_start: 424,
          excerpt: 'Before choosing a rental, after arriving, when a tenancy issue starts, when applying, and in shared housing.',
          workstreams: [
            'Product roadmap and feature research',
            'UX simplification / Codex product tasks',
          ],
        },
        {
          id: 'product-messaging',
          title: 'Messaging Angles and Reusable Copy Blocks',
          line_start: 671,
          excerpt: 'Settle in smarter, know your hood before you move, rent safer, practical arrival help, one place for alerts, evidence and next steps.',
          workstreams: [
            'Organic GTM',
            'LinkedIn content',
            'ASO / app store optimisation',
          ],
        },
      ],
    },
    {
      id: 'doc-public-sector',
      name: 'Public Sector Outreach for Hoodie.md',
      path: '/Users/rushi/Downloads/Public Sector Outreach for Hoodie.md',
      type: 'uploaded-markdown',
      imported_at: importedAt,
      last_reviewed_at: importedAt,
      sections: [
        {
          id: 'public-sector-overview',
          title: 'Strategic overview',
          line_start: 3,
          excerpt: 'Position Hoodie as a community-support, education and documentation layer for newcomers and international students, not a marketplace, legal service, university service or government platform.',
          workstreams: ['Public-sector outreach'],
        },
        {
          id: 'public-sector-directory',
          title: 'Master outreach directory',
          line_start: 39,
          excerpt: 'Federal, state, territory, agency, and council targets with outreach angles, contact methods, priority and first message type.',
          workstreams: [
            'Public-sector outreach',
            'Councils/LGAs and government contacts',
          ],
        },
        {
          id: 'public-sector-doc-pack',
          title: 'Document pack, sequencing plan and final shortlist',
          line_start: 951,
          excerpt: 'Briefing note, council one-pager, workshop outline, privacy FAQ, founder letter, pilot proposal, risk note, case-study template and impact framework.',
          workstreams: [
            'Public-sector outreach',
            'Admin, proof assets, CRM, reporting, and follow-ups',
          ],
        },
        {
          id: 'public-sector-sequence',
          title: 'Outreach sequencing plan',
          line_start: 971,
          excerpt: 'First 25 contacts, weekly activity targets, follow-up timing, CRM fields, reply segmentation and conversion actions.',
          workstreams: [
            'Public-sector outreach',
            'Councils/LGAs and government contacts',
            'Admin, proof assets, CRM, reporting, and follow-ups',
          ],
        },
      ],
    },
    {
      id: 'doc-product-opportunity',
      name: 'Product Opportunity Study for Hoodie.md',
      path: '/Users/rushi/Downloads/Product Opportunity Study for Hoodie.md',
      type: 'uploaded-markdown',
      imported_at: importedAt,
      last_reviewed_at: importedAt,
      sections: [
        {
          id: 'opportunity-top-features',
          title: 'Top ten recommended next features',
          line_start: 18,
          excerpt: 'Move-In Audit Pack, Scam Triage and Action Plan, Application Kit 2.0, Smart Evidence Vault, Suburb Compare, Repair and Bond Letter Builder, Support Handoff Hub and more.',
          workstreams: [
            'Product roadmap and feature research',
            'UX simplification / Codex product tasks',
          ],
        },
        {
          id: 'opportunity-roadmap',
          title: 'Feature roadmap',
          line_start: 317,
          excerpt: 'Month one validates hero flows, instruments events, runs interviews, prototypes top flows and defines state routing.',
          workstreams: [
            'Product roadmap and feature research',
            'UX simplification / Codex product tasks',
            'Website / landing pages / analytics setup',
          ],
        },
        {
          id: 'opportunity-metrics',
          title: 'Metrics, risks, and final recommendation',
          line_start: 459,
          excerpt: 'Activation is one meaningful hero task plus a save/export in the first seven days. Track acquisition, activation, engagement, retention, referral, trust, partner adoption and feature metrics.',
          workstreams: [
            'Website / landing pages / analytics setup',
            'Investor and pitch deck',
          ],
        },
      ],
    },
    {
      id: 'doc-organic-gtm',
      name: 'Organic GTM for Hoodie.md',
      path: '/Users/rushi/Downloads/Organic GTM for Hoodie.md',
      type: 'uploaded-markdown',
      imported_at: importedAt,
      last_reviewed_at: importedAt,
      sections: [
        {
          id: 'gtm-first-things',
          title: 'What Hoodie should do first',
          line_start: 9,
          excerpt: 'Make Hoodie your practical move-in and rent-ready companion, build partner-led landing pages, event QR onboarding, sharing loops, content engine and first urgent job activation.',
          workstreams: [
            'Organic GTM',
            'Website / landing pages / analytics setup',
            'Partner outreach',
          ],
        },
        {
          id: 'gtm-week-plan',
          title: 'Six-Month Organic GTM Plan',
          line_start: 141,
          excerpt: 'Week-by-week plan starts with positioning, partner one-pager, 3 city landing pages, 100-target CRM, content, outreach, pilots and workshop assets.',
          workstreams: [
            'Organic GTM',
            'University and admissions outreach',
            'Partner outreach',
            'Community events and workshops',
          ],
        },
        {
          id: 'gtm-events',
          title: 'Community and events strategy',
          line_start: 316,
          excerpt: 'Workshops for suburb confidence, rental scam red flags, application clinics, evidence vault, newcomer walks, share-house setup and student welcomes.',
          workstreams: [
            'Community events and workshops',
            'Organic GTM',
          ],
        },
        {
          id: 'gtm-first-30',
          title: 'Prioritised 30-day action plan',
          line_start: 502,
          excerpt: 'Daily rhythm, 100 named partner targets, 40 tailored outreaches, 10-15 conversations, 2-4 pilots, 1 event, 3 city landing pages and 12-16 posts.',
          workstreams: [
            'Organic GTM',
            'Admin, proof assets, CRM, reporting, and follow-ups',
          ],
        },
      ],
    },
    {
      id: 'doc-linkedin',
      name: 'LinkedIn for Hoodie.md',
      path: '/Users/rushi/Downloads/LinkedIn for Hoodie.md',
      type: 'uploaded-markdown',
      imported_at: importedAt,
      last_reviewed_at: importedAt,
      sections: [
        {
          id: 'linkedin-strategy',
          title: 'Strategic overview',
          line_start: 3,
          excerpt: 'LinkedIn should build founder trust, educate newcomers and partners, and open inbound conversations with councils, universities, student groups, settlement organisations, accommodation providers and local businesses.',
          workstreams: ['LinkedIn content'],
        },
        {
          id: 'linkedin-calendar',
          title: '90-day summary calendar',
          line_start: 145,
          excerpt: 'One post per day across founder reflections, educational text, carousels, videos, quote graphics, founder-style photo posts and partnership invitations.',
          workstreams: ['LinkedIn content'],
        },
        {
          id: 'linkedin-production',
          title: 'Checklist for preparing the first month of content assets',
          line_start: 3549,
          excerpt: 'Founder portrait prompts, quote graphic templates, carousel templates, video scripts, B-roll list, hashtag bank, comment bank, partner outreach list, tracking sheet and metrics dashboard.',
          workstreams: [
            'LinkedIn content',
            'Admin, proof assets, CRM, reporting, and follow-ups',
          ],
        },
      ],
    },
  ];
}

interface SeedTaskInput {
  id: string;
  title: string;
  description: string;
  source_document: string;
  source_section: string;
  source_excerpt: string;
  workstream: Workstream;
  category: TaskCategory;
  project: string;
  priority: TaskPriority;
  impact: TaskImpact;
  effort_minutes: number;
  urgency: TaskUrgency;
  day?: number;
  dependencies?: string[];
  related_partner?: string;
  related_campaign?: string;
  related_event?: string;
  related_platform?: string;
  related_city?: string;
  evidence_required?: string;
  notes?: string;
  status?: TaskStatus;
}

const seedTaskInputs: SeedTaskInput[] = [
  {
    id: 'seed-day01-crm-baseline',
    title: 'Define dashboard baseline in CRM',
    description: 'Create the minimum CRM fields needed to track Hoodie GTM, conference, public-sector, partner and follow-up execution from day one.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Outreach sequencing plan',
    source_excerpt: 'CRM fields: target name, office / role, level, state, city / electorate / LGA, portfolio, outreach angle, status, reply sentiment, next action date.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'setup',
    project: 'CRM operating system',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 1,
    evidence_required: 'CRM fields created or documented.',
  },
  {
    id: 'seed-day01-workstreams',
    title: 'Create Hoodie workstream list',
    description: 'Set up the 16 Hoodie execution workstreams exactly as operating lanes so every plan has a home.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Prioritised 30-day action plan',
    source_excerpt: 'The first 30 days should be execution-heavy and founder-led with a target dashboard rather than vanity metrics.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'setup',
    project: 'Execution dashboard setup',
    priority: 'High',
    impact: 'High',
    effort_minutes: 20,
    urgency: 'High',
    day: 1,
  },
  {
    id: 'seed-day01-positioning',
    title: 'Confirm Hoodie positioning statement',
    description: 'Lock the exact sentence used across outreach: a practical move-in and rent-ready companion, not a marketplace, legal service, university service or official platform.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'What Hoodie should do first',
    source_excerpt: 'Make Hoodie "your practical move-in and rent-ready companion in Australia".',
    workstream: 'Organic GTM',
    category: 'deep-work',
    project: 'Positioning foundation',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 1,
    evidence_required: 'One approved positioning paragraph saved.',
  },
  {
    id: 'seed-day01-review-ritual',
    title: 'Set first-week review ritual',
    description: 'Create a simple Friday review checklist for progress, blockers, source gaps, and next seven-day scheduling.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Prioritised 30-day action plan',
    source_excerpt: 'Monday review funnel metrics, Friday product tweak sprint, weekend light follow-up.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'admin',
    project: 'Founder operating cadence',
    priority: 'Medium',
    impact: 'Medium',
    effort_minutes: 20,
    urgency: 'Medium',
    day: 1,
  },
  {
    id: 'seed-day02-crm-fields',
    title: 'Create CRM fields',
    description: 'Build the live CRM table with target, organisation, category, state, workstream, status, next action and documents sent fields.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Outreach sequencing plan',
    source_excerpt: 'CRM fields include target name, office / role, level, state, city / electorate / LGA, portfolio, outreach angle and next action date.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'setup',
    project: 'CRM operating system',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 2,
    dependencies: ['seed-day01-crm-baseline'],
  },
  {
    id: 'seed-day02-first-25-public-sector',
    title: 'Add first 25 public-sector contacts',
    description: 'Load the first 25 contacts from the public-sector sequencing plan into the CRM with portfolio-specific angles.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'First 25 contacts to approach',
    source_excerpt: 'Clare O Neil, Julian Hill, Study NSW, Stephen Kamper, Anoulack Chanthivong, Ron Hoenig, City of Sydney, City of Canterbury Bankstown, and more.',
    workstream: 'Public-sector outreach',
    category: 'admin',
    project: 'First public-sector wave',
    priority: 'High',
    impact: 'High',
    effort_minutes: 40,
    urgency: 'High',
    day: 2,
    dependencies: ['seed-day02-crm-fields'],
  },
  {
    id: 'seed-day02-proof-folder',
    title: 'Create proof asset folder',
    description: 'Create a folder structure for screenshots, store metadata, workshop proof, partner notes, metrics snapshots and founder assets.',
    source_document: 'Product Opportunity Study for Hoodie.md',
    source_section: 'Metrics, risks, and final recommendation',
    source_excerpt: 'Track acquisition, activation, engagement, retention, referral, trust and partner adoption.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'asset',
    project: 'Proof assets',
    priority: 'High',
    impact: 'High',
    effort_minutes: 20,
    urgency: 'High',
    day: 2,
  },
  {
    id: 'seed-day02-evidence-checklist',
    title: 'Draft evidence checklist',
    description: 'Write the checklist of proof assets needed for outreach, ASO, investor updates and conference credibility.',
    source_document: 'hoodie-llm-product-context.md',
    source_section: 'Screenshot and Visual Reference Notes',
    source_excerpt: 'If exact screenshot files need to be attached alongside this document, the final approved screenshot pack is to be filled in.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'quick-win',
    project: 'Proof assets',
    priority: 'Medium',
    impact: 'Medium',
    effort_minutes: 20,
    urgency: 'Medium',
    day: 2,
    dependencies: ['seed-day02-proof-folder'],
  },
  {
    id: 'seed-day03-approval-pathway',
    title: 'Confirm conference approval pathway',
    description: 'Identify who must approve the High Commission conference concept, wording, date window and liaison process.',
    source_document: 'Conference Proposal.md',
    source_section: 'First 10 actions to start now',
    source_excerpt: 'Confirm approval pathway and liaison person.',
    workstream: 'Indian Student Transition and Wellbeing Forum',
    category: 'setup',
    project: 'Conference approval',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 3,
  },
  {
    id: 'seed-day03-title-purpose',
    title: 'Lock working title and public purpose',
    description: 'Choose the working conference title and one public-purpose statement that avoids commercial overreach.',
    source_document: 'Conference Proposal.md',
    source_section: 'Final recommendation',
    source_excerpt: 'Recommended event name: Beyond Admission: Indian Student Readiness for Australia.',
    workstream: 'Indian Student Transition and Wellbeing Forum',
    category: 'deep-work',
    project: 'Conference approval',
    priority: 'High',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 3,
    dependencies: ['seed-day03-approval-pathway'],
  },
  {
    id: 'seed-day03-wording-rules',
    title: 'Draft High Commission wording rules',
    description: 'Write approval-safe wording rules for public references to the High Commission, Hoodie and What\'s On responsibilities.',
    source_document: 'Conference Proposal.md',
    source_section: 'Governance and approvals',
    source_excerpt: 'All public wording will be approved before publication; no logo or official visual identity will be used without written approval.',
    workstream: 'Indian Student Transition and Wellbeing Forum',
    category: 'deep-work',
    project: 'Conference approval',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 30,
    urgency: 'High',
    day: 3,
    dependencies: ['seed-day03-title-purpose'],
  },
  {
    id: 'seed-day03-invite-tracker',
    title: 'Create conference invite tracker',
    description: 'Create the spreadsheet/table for invitees, categories, function, status, owner, source, and next action.',
    source_document: 'Conference Proposal.md',
    source_section: 'First 20 invitees or invitee groups',
    source_excerpt: 'ANU, University of Sydney, Monash, UQ, UTS, RMIT, Curtin, Charles Sturt, UNE, USQ, IEAA, ISANA, Study NSW and more.',
    workstream: 'Conference partner/sponsor/resource outreach',
    category: 'setup',
    project: 'Conference invite list',
    priority: 'High',
    impact: 'High',
    effort_minutes: 30,
    urgency: 'High',
    day: 3,
    dependencies: ['seed-day03-wording-rules'],
  },
  {
    id: 'seed-day04-linkedin-template',
    title: 'Create LinkedIn content template',
    description: 'Create a reusable post template with hook, practical lesson, subtle Hoodie mention, CTA, media prompt and metric field.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'Posting cadence',
    source_excerpt: 'One post per day for 90 days with founder reflection, education, carousel, video, quote graphic, founder photo and partnership invitation formats.',
    workstream: 'LinkedIn content',
    category: 'setup',
    project: 'LinkedIn operating system',
    priority: 'High',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 4,
  },
  {
    id: 'seed-day04-first-seven-posts',
    title: 'Prepare first 7 post checklist',
    description: 'Turn the first week of the LinkedIn calendar into a production checklist with copy, asset, schedule and engagement tasks.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'First 7 posts fully polished and ready to publish immediately',
    source_excerpt: 'Use Days 1-7 exactly as written above. They are already publication-ready in sequence.',
    workstream: 'LinkedIn content',
    category: 'content',
    project: 'LinkedIn first month',
    priority: 'High',
    impact: 'High',
    effort_minutes: 30,
    urgency: 'High',
    day: 4,
    dependencies: ['seed-day04-linkedin-template'],
  },
  {
    id: 'seed-day04-media-prompts',
    title: 'Create media prompt library',
    description: 'Create a prompt bank for founder-style images, quote graphics, carousels, videos and calm real-life settlement visuals.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'First 7 AI media prompts ready to paste into ChatGPT Images/Video',
    source_excerpt: 'The first 7 prompts are paste-ready and built for LinkedIn dimensions, tone, and brand mood.',
    workstream: 'LinkedIn content',
    category: 'asset',
    project: 'LinkedIn first month',
    priority: 'High',
    impact: 'Medium',
    effort_minutes: 30,
    urgency: 'High',
    day: 4,
    dependencies: ['seed-day04-first-seven-posts'],
  },
  {
    id: 'seed-day04-metrics-sheet',
    title: 'Set LinkedIn metrics sheet',
    description: 'Create a weekly sheet for impressions, engagement, saves, shares, profile visits, DMs, partner replies and meetings booked.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'Metrics and optimisation',
    source_excerpt: 'Track impressions, engagement rate, comments, saves, shares, profile visits, connection requests, DMs, partner replies and app clicks.',
    workstream: 'LinkedIn content',
    category: 'analytics',
    project: 'LinkedIn first month',
    priority: 'Medium',
    impact: 'Medium',
    effort_minutes: 25,
    urgency: 'Medium',
    day: 4,
    dependencies: ['seed-day04-linkedin-template'],
  },
  {
    id: 'seed-day05-partner-one-pager-outline',
    title: 'Draft partner one-pager outline',
    description: 'Outline the partner brief covering problem, safe positioning, workshop formats, resource page, QR flow, proof and CTA.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Partner map',
    source_excerpt: 'Each partner must help Hoodie borrow trust, reach a concentrated audience, host a useful event, or create a recurring referral path.',
    workstream: 'Partner outreach',
    category: 'deep-work',
    project: 'Partner asset pack',
    priority: 'High',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 5,
    dependencies: ['seed-day01-positioning'],
  },
  {
    id: 'seed-day05-city-landing-pages',
    title: 'Outline 3 city landing pages',
    description: 'Outline Sydney, Melbourne and Brisbane pages with suburb, scam, documents and share-house entry points.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Week-by-week plan',
    source_excerpt: 'Finalise homepage, partner one-pager, 3 city landing pages: Sydney, Melbourne, Brisbane.',
    workstream: 'Website / landing pages / analytics setup',
    category: 'deep-work',
    project: 'City acquisition pages',
    priority: 'High',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 5,
    dependencies: ['seed-day01-positioning'],
  },
  {
    id: 'seed-day05-utm-tags',
    title: 'Define UTM and source tags',
    description: 'Define partner, city, campaign and event source tags before outreach or QR distribution starts.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Funnel and activation design',
    source_excerpt: 'Track landing_view, partner_lp_view, content_click, qr_scan, cta_click, persona_select, city_select and activation events.',
    workstream: 'Website / landing pages / analytics setup',
    category: 'analytics',
    project: 'Acquisition instrumentation',
    priority: 'High',
    impact: 'High',
    effort_minutes: 20,
    urgency: 'High',
    day: 5,
  },
  {
    id: 'seed-day05-warm-contacts',
    title: 'Pick first 20 warm contacts',
    description: 'Select first warm contacts across universities, student hubs, councils, associations and community operators.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'First 30 days by week',
    source_excerpt: 'Days 1-7: finalise positioning, one-pager, 3 city LPs, outreach list of 100 targets and 20 university/student/city contacts.',
    workstream: 'Organic GTM',
    category: 'outreach',
    project: 'Warm outreach wave',
    priority: 'High',
    impact: 'High',
    effort_minutes: 20,
    urgency: 'High',
    day: 5,
    dependencies: ['seed-day02-crm-fields'],
  },
  {
    id: 'seed-day06-briefing-note',
    title: 'Draft public-sector briefing note',
    description: 'Draft the one-page civic-language note for ministers, advisers and agency leads.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Document directory',
    source_excerpt: 'Public-sector briefing note: problem, audience, what Hoodie does, what it does not do, partnership options, 20-minute briefing CTA.',
    workstream: 'Public-sector outreach',
    category: 'deep-work',
    project: 'Public-sector document pack',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 40,
    urgency: 'High',
    day: 6,
    dependencies: ['seed-day01-positioning'],
  },
  {
    id: 'seed-day06-council-one-pager',
    title: 'Draft council one-pager',
    description: 'Draft the council-specific one-pager with local problem, workshop formats, venue ideas, referral pathways and community outcomes.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Document directory',
    source_excerpt: 'Council partnership one-pager: local problem, workshop formats, venue ideas, referral pathways, outcomes, short scoping call.',
    workstream: 'Councils/LGAs and government contacts',
    category: 'deep-work',
    project: 'Public-sector document pack',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 6,
    dependencies: ['seed-day06-briefing-note'],
  },
  {
    id: 'seed-day06-compliance-guardrails',
    title: 'Prepare compliance guardrails',
    description: 'Turn public-sector reputation rules into a reusable checklist attached to every outreach task.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Compliance and reputation guardrails',
    source_excerpt: 'Do not imply Hoodie is official, endorsed or guaranteed. Keep asks modest and community-focused.',
    workstream: 'Public-sector outreach',
    category: 'review',
    project: 'Public-sector document pack',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 6,
    dependencies: ['seed-day06-briefing-note'],
  },
  {
    id: 'seed-day06-follow-up-cadence',
    title: 'Create public-sector follow-up cadence',
    description: 'Create the day 0, day 3-4, day 8-10, day 21 and 6-8 week follow-up rules in the CRM.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Follow-up timing',
    source_excerpt: 'Day 0 initial email/form, day 3-4 follow-up or call, day 8-10 second follow-up, day 21 close loop, then pause.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'follow-up',
    project: 'CRM operating system',
    priority: 'High',
    impact: 'Medium',
    effort_minutes: 20,
    urgency: 'High',
    day: 6,
    dependencies: ['seed-day02-crm-fields'],
  },
  {
    id: 'seed-day07-hero-flows',
    title: 'Map top 3 product hero flows',
    description: 'Map Move-In Audit Pack, Scam Triage and Application Kit 2.0 as scenario flows with entry, output, share/export and metric.',
    source_document: 'Product Opportunity Study for Hoodie.md',
    source_section: 'Top three to build first',
    source_excerpt: 'The best first build sequence is Move-In Audit Pack, Scam Triage and Action Plan, Application Kit 2.0.',
    workstream: 'Product roadmap and feature research',
    category: 'deep-work',
    project: 'Hero flow validation',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 7,
  },
  {
    id: 'seed-day07-baseline-events',
    title: 'Define baseline analytics events',
    description: 'Create event definitions for hero flow selected, started, completed, exported, shared and official handoff clicked.',
    source_document: 'Product Opportunity Study for Hoodie.md',
    source_section: 'Organic funnel and activation design',
    source_excerpt: 'A user is activated if, in their first seven days, they complete one meaningful hero task and save or export something.',
    workstream: 'Website / landing pages / analytics setup',
    category: 'analytics',
    project: 'Hero flow validation',
    priority: 'High',
    impact: 'High',
    effort_minutes: 30,
    urgency: 'High',
    day: 7,
    dependencies: ['seed-day07-hero-flows'],
  },
  {
    id: 'seed-day07-interview-script',
    title: 'Create hero-flow interview script',
    description: 'Write interview prompts for international students, newcomers and first-time renters around moving in, scam checks and applications.',
    source_document: 'Product Opportunity Study for Hoodie.md',
    source_section: 'Experiment plan before building',
    source_excerpt: 'Run 10 interviews with international students, recent migrants and first-time renters.',
    workstream: 'Product roadmap and feature research',
    category: 'research',
    project: 'Hero flow validation',
    priority: 'High',
    impact: 'Medium',
    effort_minutes: 25,
    urgency: 'High',
    day: 7,
    dependencies: ['seed-day07-hero-flows'],
  },
  {
    id: 'seed-day07-recruit-testers',
    title: 'Recruit 5 testers',
    description: 'Send five tester asks for the top hero-flow interviews/prototype review.',
    source_document: 'Product Opportunity Study for Hoodie.md',
    source_section: 'First thirty-day action plan',
    source_excerpt: 'Run 10 interviews with international students, recent migrants and first-time renters.',
    workstream: 'Product roadmap and feature research',
    category: 'outreach',
    project: 'Hero flow validation',
    priority: 'Medium',
    impact: 'Medium',
    effort_minutes: 25,
    urgency: 'Medium',
    day: 7,
    dependencies: ['seed-day07-interview-script'],
  },
  {
    id: 'seed-day08-speakers',
    title: 'Identify 12 conference speakers',
    description: 'Create a speaker shortlist across High Commission, PVC International, admissions, wellbeing, OSHC, tenancy, employability and accommodation roles.',
    source_document: 'Conference Proposal.md',
    source_section: 'First 10 speaker or facilitator types',
    source_excerpt: 'High Commission representative, PVC International, international admissions, student experience, wellbeing, OSHC, tenancy, careers, accommodation and neutral moderator.',
    workstream: 'Conference partner/sponsor/resource outreach',
    category: 'outreach',
    project: 'Conference speaker pipeline',
    priority: 'High',
    impact: 'High',
    effort_minutes: 30,
    urgency: 'High',
    day: 8,
    dependencies: ['seed-day03-invite-tracker'],
  },
  {
    id: 'seed-day08-speaker-brief',
    title: 'Draft speaker brief',
    description: 'Draft the one-page session brief plus what-not-to-say note for sensitive visa, health, tenancy and legal topics.',
    source_document: 'Conference Proposal.md',
    source_section: 'Speaker management',
    source_excerpt: 'Invite speakers with a one-page session brief and require a what-not-to-say note for visa, health, tenancy and legal sessions.',
    workstream: 'Conference partner/sponsor/resource outreach',
    category: 'deep-work',
    project: 'Conference speaker pipeline',
    priority: 'High',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 8,
    dependencies: ['seed-day03-wording-rules'],
  },
  {
    id: 'seed-day08-landing-registration',
    title: 'Outline conference landing page and registration fields',
    description: 'Turn the event landing page structure and registration fields into an implementation-ready outline.',
    source_document: 'Conference Proposal.md',
    source_section: 'Registration flow',
    source_excerpt: 'Collect first/last name, organisation, role, email, city/state, organisation type, relevant functions, pilot interest and follow-up consent.',
    workstream: 'Indian Student Transition and Wellbeing Forum',
    category: 'deep-work',
    project: 'Conference registration',
    priority: 'High',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 8,
    dependencies: ['seed-day03-wording-rules'],
  },
  {
    id: 'seed-day08-approval-meeting',
    title: 'Schedule approval meeting ask',
    description: 'Prepare and send the short ask for an approval meeting or liaison confirmation.',
    source_document: 'Conference Proposal.md',
    source_section: 'Next steps',
    source_excerpt: 'Hold a short approval meeting, confirm preferred event title, date window, authorised wording, liaison, invitee categories and invitation email.',
    workstream: 'Indian Student Transition and Wellbeing Forum',
    category: 'outreach',
    project: 'Conference approval',
    priority: 'Critical',
    impact: 'High',
    effort_minutes: 20,
    urgency: 'High',
    day: 8,
    dependencies: ['seed-day03-wording-rules'],
  },
  {
    id: 'seed-day09-polish-posts',
    title: 'Polish LinkedIn Days 1-3 posts',
    description: 'Finalise the first three LinkedIn posts so they are ready to schedule without needing another content pass.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'Days 1-30',
    source_excerpt: 'Day 1 next stage after What\'s On; Day 2 from events to practical support; Day 3 why we are building Hoodie.',
    workstream: 'LinkedIn content',
    category: 'content',
    project: 'LinkedIn first week',
    priority: 'High',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 9,
    dependencies: ['seed-day04-first-seven-posts'],
  },
  {
    id: 'seed-day09-first-visuals',
    title: 'Generate or collect first 3 LinkedIn visuals',
    description: 'Create founder-style image, carousel base and video/cover visual for Days 1-3.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'First 7 AI media prompts ready to paste into ChatGPT Images/Video',
    source_excerpt: 'The first 7 prompts are paste-ready and built for LinkedIn dimensions, tone, and brand mood.',
    workstream: 'LinkedIn content',
    category: 'asset',
    project: 'LinkedIn first week',
    priority: 'High',
    impact: 'Medium',
    effort_minutes: 35,
    urgency: 'High',
    day: 9,
    dependencies: ['seed-day04-media-prompts'],
  },
  {
    id: 'seed-day09-schedule-first-post',
    title: 'Schedule first LinkedIn post',
    description: 'Load the first Hoodie narrative bridge post into the scheduler with first comment and tracking link.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'Simple content production workflow for batching 30 days',
    source_excerpt: 'Scheduling day: load posts into scheduler, prepare first comment for each, set reminder for engagement.',
    workstream: 'LinkedIn content',
    category: 'quick-win',
    project: 'LinkedIn first week',
    priority: 'Medium',
    impact: 'Medium',
    effort_minutes: 20,
    urgency: 'Medium',
    day: 9,
    dependencies: ['seed-day09-polish-posts'],
  },
  {
    id: 'seed-day09-comment-bank',
    title: 'Build comment-response bank',
    description: 'Write 10 warm, practical reply patterns for comments from councils, university teams, student leaders and founders.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'Engagement strategy',
    source_excerpt: 'Reply to comments with extra practical detail, not thanks; if a council or university person engages twice, send a specific DM.',
    workstream: 'LinkedIn content',
    category: 'admin',
    project: 'LinkedIn first week',
    priority: 'Medium',
    impact: 'Medium',
    effort_minutes: 25,
    urgency: 'Medium',
    day: 9,
    dependencies: ['seed-day04-linkedin-template'],
  },
  {
    id: 'seed-day10-finalise-partner-brief',
    title: 'Finalise partner brief',
    description: 'Turn the partner one-pager outline into a sendable one-page PDF/doc with safe language and a workshop CTA.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Partner map',
    source_excerpt: 'What Hoodie can offer: practical renter-readiness workshops, city pages, QR onboarding, referral-safe handouts.',
    workstream: 'Partner outreach',
    category: 'deep-work',
    project: 'Partner asset pack',
    priority: 'High',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 10,
    dependencies: ['seed-day05-partner-one-pager-outline'],
  },
  {
    id: 'seed-day10-university-targets',
    title: 'Add 25 university and student targets',
    description: 'Add universities, student associations, study bodies and student hubs into CRM with recommended first ask.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Partner map',
    source_excerpt: 'Universities need students supported between pre-arrival and off-campus life; ask for session slot, digital resource listing, or student comms mention.',
    workstream: 'University and admissions outreach',
    category: 'admin',
    project: 'University outreach wave',
    priority: 'High',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'High',
    day: 10,
    dependencies: ['seed-day02-crm-fields'],
  },
  {
    id: 'seed-day10-first-warm-messages',
    title: 'Send first 5 warm partner messages',
    description: 'Send five low-pressure warm messages using the partner brief and log next actions.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'First 30 days by week',
    source_excerpt: 'Days 8-14: send 30 to 40 tailored messages, book 6 to 8 calls, run 5 interviews.',
    workstream: 'Partner outreach',
    category: 'outreach',
    project: 'Warm outreach wave',
    priority: 'High',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 10,
    dependencies: ['seed-day10-finalise-partner-brief', 'seed-day05-warm-contacts'],
  },
  {
    id: 'seed-day10-log-follow-ups',
    title: 'Log first warm outreach follow-ups',
    description: 'Create follow-up dates and next actions for every warm message sent today.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Follow-up timing',
    source_excerpt: 'Day 3-4: polite follow-up or call.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'follow-up',
    project: 'CRM operating system',
    priority: 'Medium',
    impact: 'Medium',
    effort_minutes: 20,
    urgency: 'Medium',
    day: 10,
    dependencies: ['seed-day10-first-warm-messages'],
  },
  {
    id: 'seed-day11-screenshot-gaps',
    title: 'List store screenshot gaps',
    description: 'Compare current app features against screenshots needed for store conversion: Arrival, Vibe, map alerts, evidence vault, application kit, household.',
    source_document: 'hoodie-llm-product-context.md',
    source_section: 'Screenshot and Visual Reference Notes',
    source_excerpt: 'Current visual references include splash, household overview, Vibe guide imagery and map-led product surfaces.',
    workstream: 'ASO / app store optimisation',
    category: 'asset',
    project: 'ASO prerequisites',
    priority: 'High',
    impact: 'Medium',
    effort_minutes: 25,
    urgency: 'Medium',
    day: 11,
  },
  {
    id: 'seed-day13-metric-gaps',
    title: 'Collect investor metric gaps',
    description: 'List missing metrics needed for a credible investor update: users, activation, retention, partner pipeline, installs, workshops and proof.',
    source_document: 'Product Opportunity Study for Hoodie.md',
    source_section: 'Key metrics framework',
    source_excerpt: 'Track acquisition, activation, engagement, retention, referral, trust and safety, partner adoption and feature-specific metrics.',
    workstream: 'Investor and pitch deck',
    category: 'research',
    project: 'Pitch proof system',
    priority: 'High',
    impact: 'High',
    effort_minutes: 30,
    urgency: 'Medium',
    day: 13,
    dependencies: ['seed-day02-proof-folder'],
  },
  {
    id: 'seed-day13-narrative-outline',
    title: 'Outline pitch narrative',
    description: 'Outline the story from What\'s On community trust to Hoodie practical settlement, rental safety and evidence organisation.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'The founder-brand angle',
    source_excerpt: 'What\'s On helped people discover community. Hoodie is about helping people feel steadier inside it.',
    workstream: 'Investor and pitch deck',
    category: 'deep-work',
    project: 'Pitch proof system',
    priority: 'High',
    impact: 'High',
    effort_minutes: 30,
    urgency: 'Medium',
    day: 13,
    dependencies: ['seed-day13-metric-gaps'],
  },
  {
    id: 'seed-day14-weekly-review',
    title: 'Complete weekly review',
    description: 'Review all completed, not done, skipped, blocked, waiting and deferred work from the first two weeks.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Daily operating rhythm',
    source_excerpt: 'Monday review funnel metrics and top user questions; Friday product tweak sprint; weekend light DM follow-up.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'review',
    project: 'Founder operating cadence',
    priority: 'High',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 14,
    dependencies: ['seed-day01-review-ritual'],
  },
  {
    id: 'seed-day14-progress-readiness',
    title: 'Update progress and readiness metrics',
    description: 'Update workstream progress, conference readiness, LinkedIn readiness, ads setup readiness, ASO readiness and pitch readiness.',
    source_document: 'Product Opportunity Study for Hoodie.md',
    source_section: 'Metrics, risks, and final recommendation',
    source_excerpt: 'Use targets, not vanity metrics, and review activation, partner adoption, feature-specific and proof metrics.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'analytics',
    project: 'Founder operating cadence',
    priority: 'High',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 14,
    dependencies: ['seed-day14-weekly-review'],
  },
  {
    id: 'seed-day14-unblock-waiting',
    title: 'Unblock waiting items',
    description: 'Review blocked or waiting items and set one concrete unblock step or follow-up date for each.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Convert replies into action',
    source_excerpt: 'Meeting -> send one-page note same day; referral -> ask permission to reference their name; interesting but not us -> ask for one better contact.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'follow-up',
    project: 'Founder operating cadence',
    priority: 'High',
    impact: 'Medium',
    effort_minutes: 25,
    urgency: 'High',
    day: 14,
    dependencies: ['seed-day14-weekly-review'],
  },
  {
    id: 'seed-day14-next-plan',
    title: 'Generate next 7-day plan',
    description: 'Use the scheduler to generate a balanced next seven days after reviewing dependencies, blockers and source gaps.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Prioritised 30-day action plan',
    source_excerpt: 'The first 30 days should be execution-heavy and founder-led.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'setup',
    project: 'Founder operating cadence',
    priority: 'High',
    impact: 'High',
    effort_minutes: 25,
    urgency: 'High',
    day: 14,
    dependencies: ['seed-day14-progress-readiness'],
  },
  {
    id: 'seed-day14-archive-duplicates',
    title: 'Archive or merge duplicate tasks',
    description: 'Merge duplicate tasks and archive stale assumptions so the dashboard stays light enough to use daily.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Reply segmentation',
    source_excerpt: 'No response pauses after three touches; too early moves to 60-day re-approach list.',
    workstream: 'Admin, proof assets, CRM, reporting, and follow-ups',
    category: 'review',
    project: 'Founder operating cadence',
    priority: 'Medium',
    impact: 'Medium',
    effort_minutes: 20,
    urgency: 'Medium',
    day: 14,
    dependencies: ['seed-day14-weekly-review'],
  },
  {
    id: 'backlog-public-sector-first-emails',
    title: 'Send first 5 public-sector emails',
    description: 'Send the first five tailored public-sector notes only after the briefing note, council one-pager and guardrails exist.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Weekly activity targets',
    source_excerpt: '12-15 initial emails, 5-8 calls, 8-10 LinkedIn requests, 4-6 follow-ups, 2 document sends after interest.',
    workstream: 'Public-sector outreach',
    category: 'outreach',
    project: 'First public-sector wave',
    priority: 'High',
    impact: 'High',
    effort_minutes: 45,
    urgency: 'High',
    dependencies: ['seed-day06-briefing-note', 'seed-day06-council-one-pager', 'seed-day06-compliance-guardrails'],
  },
  {
    id: 'backlog-council-workshop-outline',
    title: 'Draft council workshop outline',
    description: 'Draft the Know your suburb before you move workshop outline with council role, Hoodie role, CTA and risk guardrails.',
    source_document: 'Public Sector Outreach for Hoodie.md',
    source_section: 'Example council event proposal',
    source_excerpt: '45-minute workshop hosted at library/community hub/student welcome venue with suburb fit, rental red flags, documents and local support.',
    workstream: 'Councils/LGAs and government contacts',
    category: 'deep-work',
    project: 'Council pilot pack',
    priority: 'High',
    impact: 'High',
    effort_minutes: 40,
    urgency: 'Medium',
    dependencies: ['seed-day06-council-one-pager'],
  },
  {
    id: 'backlog-eoi-form',
    title: 'Build pilot EOI form draft',
    description: 'Create the pilot expression-of-interest form from the conference proposal fields.',
    source_document: 'Conference Proposal.md',
    source_section: 'Draft pilot expression-of-interest form',
    source_excerpt: 'Institution, contact, title, email, city/state, organisation type, cohort size, journey supported, pilot use cases, champion nomination and follow-up interest.',
    workstream: 'Indian Student Transition and Wellbeing Forum',
    category: 'setup',
    project: 'Conference pilot flow',
    priority: 'High',
    impact: 'High',
    effort_minutes: 40,
    urgency: 'Medium',
    dependencies: ['seed-day08-landing-registration'],
  },
  {
    id: 'backlog-resource-pack-outline',
    title: 'Assemble resource pack outline',
    description: 'Turn the conference resource pack outline into a working folder and table of contents.',
    source_document: 'Conference Proposal.md',
    source_section: 'Draft resource pack outline',
    source_excerpt: 'Conference summary, approved slide deck, pre-arrival checklist, housing readiness guide, official links, OSHC sheet, work rights sheet and referral map.',
    workstream: 'Conference partner/sponsor/resource outreach',
    category: 'asset',
    project: 'Conference resources',
    priority: 'High',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'Medium',
    dependencies: ['seed-day03-wording-rules'],
  },
  {
    id: 'backlog-product-state-routing',
    title: 'Define state-routing content model',
    description: 'Define the first NSW/VIC routing model for legal-prep, support handoff and official-source links.',
    source_document: 'Product Opportunity Study for Hoodie.md',
    source_section: 'Current gaps',
    source_excerpt: 'State-specific friction matters because renting rights and dispute pathways differ by jurisdiction; onboarding should route by state or territory early.',
    workstream: 'UX simplification / Codex product tasks',
    category: 'deep-work',
    project: 'Hero flow validation',
    priority: 'High',
    impact: 'High',
    effort_minutes: 45,
    urgency: 'Medium',
    dependencies: ['seed-day07-hero-flows'],
  },
  {
    id: 'backlog-prototype-move-in-pack',
    title: 'Prototype Move-In Audit Pack',
    description: 'Create a paper/Figma prototype for the Move-In Audit Pack with output artifact and proof checklist.',
    source_document: 'Product Opportunity Study for Hoodie.md',
    source_section: 'Experiment plan before building',
    source_excerpt: 'Test Move-In Audit Pack with Figma prototype and concierge beta via Google Drive export.',
    workstream: 'Product roadmap and feature research',
    category: 'deep-work',
    project: 'Hero flow validation',
    priority: 'High',
    impact: 'High',
    effort_minutes: 45,
    urgency: 'Medium',
    dependencies: ['seed-day07-hero-flows', 'seed-day07-interview-script'],
  },
  {
    id: 'backlog-website-homepage-audit',
    title: 'Audit homepage first urgent job',
    description: 'Check whether the homepage and first click clearly route to one urgent job: suburb confidence, scam red flags, application readiness or evidence logging.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Funnel and activation design',
    source_excerpt: 'The first activation event should not be complete profile. It should be solve one urgent task.',
    workstream: 'Website / landing pages / analytics setup',
    category: 'review',
    project: 'Acquisition instrumentation',
    priority: 'High',
    impact: 'High',
    effort_minutes: 35,
    urgency: 'Medium',
    dependencies: ['seed-day05-city-landing-pages'],
  },
  {
    id: 'backlog-linkedin-week2',
    title: 'Batch LinkedIn Week 2 posts',
    description: 'Prepare Days 8-14 around early newcomer support, first-week checklist, timing/context/confidence and founder photo.',
    source_document: 'LinkedIn for Hoodie.md',
    source_section: 'Days 1-30',
    source_excerpt: 'Days 8-14 cover early newcomer support, first-week checklist, timing, context, confidence and founder journey.',
    workstream: 'LinkedIn content',
    category: 'content',
    project: 'LinkedIn first month',
    priority: 'High',
    impact: 'High',
    effort_minutes: 45,
    urgency: 'Medium',
    dependencies: ['seed-day09-polish-posts'],
  },
  {
    id: 'backlog-first-workshop-script',
    title: 'Draft first workshop run sheet',
    description: 'Draft a 45-minute Know your suburb before you move workshop with agenda, materials, CTA and follow-up.',
    source_document: 'Organic GTM for Hoodie.md',
    source_section: 'Community and events strategy',
    source_excerpt: 'Know your suburb before you move: suburb factors, transport, groceries, safety mindset, what to check before committing, slides, worksheet and QR cards.',
    workstream: 'Community events and workshops',
    category: 'deep-work',
    project: 'First workshop',
    priority: 'High',
    impact: 'High',
    effort_minutes: 45,
    urgency: 'Medium',
    dependencies: ['seed-day10-finalise-partner-brief'],
  },
];

function buildTasks(baseDate: Date, now: Date): ExecutionTask[] {
  const createdAt = isoNow(now);
  let undatedCounter = 0;
  const sourcedInputs = seedTaskInputs.filter((input) =>
    isApprovedSeedSourceDocumentName(input.source_document),
  );
  const sourceTaskIds = new Set(sourcedInputs.map((input) => input.id));
  const tasks = sourcedInputs.map((input, index): ExecutionTask => {
    const assignedDay = input.day || 15 + undatedCounter;
    if (!input.day) undatedCounter += 1;
    const assignedDate = dateFromDay(baseDate, assignedDay);
    return {
      id: input.id,
      title: input.title,
      description: input.description,
      source_document: input.source_document,
      source_section: input.source_section,
      source_excerpt: input.source_excerpt,
      workstream: input.workstream,
      category: input.category,
      project: input.project,
      priority: input.priority,
      impact: input.impact,
      effort_minutes: input.effort_minutes,
      urgency: input.urgency,
      status: input.status || 'Not started',
      scheduled_date: assignedDate,
      due_date: assignedDate,
      dependencies: (input.dependencies || []).filter((dependencyId) => sourceTaskIds.has(dependencyId)),
      prerequisite_of: [],
      sequence_order: index + 1,
      owner: FOUNDER_OWNER,
      related_partner: input.related_partner,
      related_campaign: input.related_campaign,
      related_event: input.related_event,
      related_platform: input.related_platform,
      related_city: input.related_city,
      notes: input.notes,
      evidence_required: input.evidence_required,
      completion_proof: '',
      ai_generated: true,
      manually_added: false,
      created_at: createdAt,
      updated_at: createdAt,
    };
  });

  const byId = new Map(tasks.map((task) => [task.id, task]));
  for (const task of tasks) {
    for (const dependencyId of task.dependencies) {
      const dependency = byId.get(dependencyId);
      if (dependency && !dependency.prerequisite_of.includes(task.id)) {
        dependency.prerequisite_of.push(task.id);
      }
    }
  }

  return tasks;
}

function createCandidateTasks(baseDate: Date, now: Date): ExtractedTaskCandidate[] {
  void baseDate;
  void now;
  return [];
}

export function createInitialExecutionState(now = new Date()): ExecutionState {
  const createdAt = isoNow(now);
  const tasks = buildTasks(now, now);
  const today = toISODate(now);
  const todayTaskIds = tasks
    .filter((task) => task.scheduled_date === today)
    .map((task) => task.id);

  return {
    version: EXECUTION_STORAGE_VERSION,
    source_documents: sourceDocuments(now),
    tasks,
    candidate_tasks: createCandidateTasks(now, now),
    daily_plans: [
      {
        id: `plan-${today}`,
        date: today,
        task_ids: todayTaskIds,
        target_minutes: 120,
        locked_task_ids: [],
        generated_at: createdAt,
        planner_version: 'seed-v2',
      },
    ],
    analytics_events: [],
    settings: {
      target_daily_minutes: 120,
      min_daily_minutes: 90,
      max_daily_minutes: 135,
      founder_name: 'Founder',
    },
    created_at: createdAt,
    updated_at: createdAt,
  };
}
