import type { AgentsDashboardData } from './types';

export const mockAgentsDashboard: AgentsDashboardData = {
  session: {
    agency: {
      id: 'agency-demo-hoodie',
      name: 'Hoodie Pilot Realty',
      timezone: 'Australia/Sydney',
      plan: 'Pilot',
    },
    user: {
      id: 'user-demo-agency-admin',
      agency_id: 'agency-demo-hoodie',
      role_id: 'role-agency-admin',
      email: 'pilot.admin@hoodieforagents.test',
      name: 'Pilot Admin',
      status: 'active',
      role: 'Agency Admin',
    },
    permissions: [
      'dashboard:read',
      'contacts:read',
      'contacts:create',
      'properties:read',
      'applications:read',
      'maintenance:read',
      'ai_runs:create',
      'ai_runs:approve',
      'audit_logs:read',
      'integrations:admin',
    ],
  },
  metrics: [
    { id: 'inbox', label: 'Inbox needing action', value: '18', trend: '-22% from baseline', tone: 'good' },
    { id: 'apps', label: 'Applications incomplete', value: '7', trend: '3 waiting on applicants', tone: 'warn' },
    { id: 'maintenance', label: 'Open maintenance timelines', value: '12', trend: '2 owner updates due', tone: 'risk' },
    { id: 'approvals', label: 'AI drafts awaiting approval', value: '5', trend: '0 sent automatically', tone: 'neutral' },
  ],
  priority_queue: [
    {
      id: 'queue-ai-draft-1',
      type: 'ai_approval',
      title: 'Approve tenant reply draft',
      entity: 'Unit 4, 18 Park Street',
      owner: 'Maya Chen',
      due: 'Today 11:30',
      priority: 'high',
      status: 'Awaiting human approval',
    },
    {
      id: 'queue-app-1',
      type: 'application',
      title: 'Request missing payslips and pet declaration',
      entity: 'Application APP-1042',
      owner: 'Leasing Queue',
      due: 'Today',
      priority: 'medium',
      status: 'Completeness only',
    },
    {
      id: 'queue-maint-1',
      type: 'maintenance',
      title: 'Kitchen leak timeline needs vendor handoff',
      entity: 'Issue MNT-882',
      owner: 'Ari Patel',
      due: 'Overdue',
      priority: 'urgent',
      status: 'PM confirmation required',
    },
    {
      id: 'queue-inspection-1',
      type: 'inspection',
      title: 'Confirm inspection attendance list',
      entity: '12 Harbour Road',
      owner: 'Sofia Nguyen',
      due: 'Tomorrow 9:00',
      priority: 'low',
      status: 'Calendar draft',
    },
  ],
  approval_queue: [
    {
      id: 'ai-run-001',
      agent: 'PM Inbox Agent',
      object_type: 'conversation_thread',
      object_id: 'thread-001',
      output:
        'Draft reply: Thanks for sending through the leak photos. We have logged the issue, attached the evidence to the maintenance timeline, and will confirm the vendor attendance window before sharing any owner update.',
      confidence: 0.84,
      sources: ['Email thread TH-001', 'Maintenance issue MNT-882', 'Agency SOP: Repairs intake'],
      status: 'drafted',
      requires_approval: true,
      created_at: '2026-05-03T00:15:00.000Z',
    },
    {
      id: 'ai-run-002',
      agent: 'Applicant Readiness Agent',
      object_type: 'application',
      object_id: 'app-1042',
      output:
        'Completeness check: proof of income and pet declaration are missing. This is not a suitability score and cannot be used as an application decision.',
      confidence: 0.91,
      sources: ['Application APP-1042', 'Readiness checklist v1'],
      status: 'drafted',
      requires_approval: true,
      created_at: '2026-05-03T00:22:00.000Z',
    },
  ],
  contacts: [
    {
      id: 'contact-tenant-1',
      name: 'Priya Shah',
      email: 'priya@example.com',
      phone: '+61 400 111 222',
      role: 'tenant',
      consent_status: 'pending',
      last_touch: 'Leak photos received 18 min ago',
    },
    {
      id: 'contact-applicant-1',
      name: 'Noah Williams',
      email: 'noah@example.com',
      phone: '+61 411 444 555',
      role: 'applicant',
      consent_status: 'granted',
      last_touch: 'Application imported today',
    },
    {
      id: 'contact-owner-1',
      name: 'Eleanor Lee',
      email: 'owner@example.com',
      phone: '+61 422 777 888',
      role: 'landlord',
      consent_status: 'not_required',
      last_touch: 'Owner update due',
    },
  ],
  properties: [
    {
      id: 'property-001',
      address: 'Unit 4, 18 Park Street, Sydney NSW',
      owner: 'Eleanor Lee',
      manager: 'Ari Patel',
      status: 'maintenance',
      open_items: 3,
    },
    {
      id: 'property-002',
      address: '12 Harbour Road, Wollongong NSW',
      owner: 'Marcus Bell',
      manager: 'Maya Chen',
      status: 'listed',
      open_items: 5,
    },
  ],
  applications: [
    {
      id: 'app-1042',
      applicant: 'Noah Williams',
      property: '12 Harbour Road',
      stage: 'Incomplete',
      readiness_status: 'missing_info',
      missing_items: ['Proof of income', 'Pet declaration'],
      source: 'Mock 2Apply connector',
    },
    {
      id: 'app-1043',
      applicant: 'Aisha Khan',
      property: 'Unit 4, 18 Park Street',
      stage: 'Ready for PM',
      readiness_status: 'ready_for_review',
      missing_items: [],
      source: 'Mock Snug connector',
    },
  ],
  maintenance_issues: [
    {
      id: 'mnt-882',
      title: 'Kitchen leak reported with photo evidence',
      property: 'Unit 4, 18 Park Street',
      tenant: 'Priya Shah',
      urgency: 'urgent',
      status: 'triage',
      timeline_count: 6,
    },
    {
      id: 'mnt-883',
      title: 'Intermittent balcony door latch',
      property: '12 Harbour Road',
      tenant: 'Vacant listing',
      urgency: 'routine',
      status: 'new',
      timeline_count: 2,
    },
  ],
  integrations: [
    {
      id: 'integration-mock-pm',
      provider: 'mock_property_manager',
      label: 'Mock PM system',
      status: 'mock',
      scopes: ['properties:read', 'contacts:read', 'maintenance:read'],
      last_sync_at: '2026-05-03T00:10:00.000Z',
    },
    {
      id: 'integration-mock-apps',
      provider: 'mock_application_platform',
      label: 'Mock application platform',
      status: 'mock',
      scopes: ['applications:read', 'documents:read'],
      last_sync_at: '2026-05-03T00:18:00.000Z',
    },
  ],
  audit_logs: [
    {
      id: 'audit-001',
      action: 'ai_run_created',
      object_type: 'ai_agent_run',
      object_id: 'ai-run-001',
      actor: 'pilot.admin@hoodieforagents.test',
      created_at: '2026-05-03T00:15:00.000Z',
    },
    {
      id: 'audit-002',
      action: 'integration_connected',
      object_type: 'integration_connection',
      object_id: 'integration-mock-pm',
      actor: 'pilot.admin@hoodieforagents.test',
      created_at: '2026-05-03T00:10:00.000Z',
    },
  ],
  threads: [
    {
      id: 'thread-001',
      subject: 'Kitchen leak photos and access window',
      linked_object: 'MNT-882',
      channel: 'email',
      status: 'open',
      summary: 'Tenant sent photos, PM needs to confirm vendor attendance and owner-safe update wording.',
    },
    {
      id: 'thread-002',
      subject: 'Inspection enquiry for 12 Harbour Road',
      linked_object: 'Lead LD-204',
      channel: 'portal',
      status: 'waiting',
      summary: 'Applicant asked for inspection times. AI can draft options but cannot send without approval.',
    },
  ],
  tasks: [
    {
      id: 'task-001',
      title: 'Confirm plumber availability before sending owner update',
      owner: 'Ari Patel',
      due: 'Today',
      status: 'open',
      linked_object: 'MNT-882',
    },
    {
      id: 'task-002',
      title: 'Review APP-1042 missing-document request',
      owner: 'Leasing Queue',
      due: 'Today',
      status: 'waiting',
      linked_object: 'APP-1042',
    },
  ],
};
