export const australianUniversities = [
  "Australian Catholic University",
  "Australian National University",
  "Bond University",
  "Carnegie Mellon University Australia",
  "Central Queensland University",
  "Charles Darwin University",
  "Charles Sturt University",
  "Curtin University",
  "Deakin University",
  "Edith Cowan University",
  "Federation University Australia",
  "Flinders University",
  "Griffith University",
  "James Cook University",
  "La Trobe University",
  "Macquarie University",
  "Monash University",
  "Murdoch University",
  "Queensland University of Technology",
  "RMIT University",
  "Southern Cross University",
  "Swinburne University of Technology",
  "Torrens University Australia",
  "University of Adelaide",
  "University of Canberra",
  "University of Divinity",
  "University of Melbourne",
  "University of New England",
  "University of New South Wales",
  "University of Newcastle",
  "University of Notre Dame Australia",
  "University of Queensland",
  "University of South Australia",
  "University of Southern Queensland",
  "University of Sydney",
  "University of Tasmania",
  "University of Technology Sydney",
  "University of the Sunshine Coast",
  "University of Western Australia",
  "University of Wollongong",
  "Victoria University",
  "Western Sydney University",
];

export const universityCoordinates: Record<string, { lat: number; lng: number }> = {
  "Australian Catholic University": { lat: -33.8800, lng: 151.2100 },
  "Australian National University": { lat: -35.2777, lng: 149.1185 },
  "Bond University": { lat: -28.0735, lng: 153.4160 },
  "Carnegie Mellon University Australia": { lat: -37.8525, lng: 144.9803 },
  "Central Queensland University": { lat: -23.3215, lng: 150.5209 },
  "Charles Darwin University": { lat: -12.3714, lng: 130.8694 },
  "Charles Sturt University": { lat: -35.0655, lng: 147.3542 },
  "Curtin University": { lat: -32.0054, lng: 115.8942 },
  "Deakin University": { lat: -38.1970, lng: 144.2952 },
  "Edith Cowan University": { lat: -31.7513, lng: 115.7739 },
  "Federation University Australia": { lat: -37.5622, lng: 143.8503 },
  "Flinders University": { lat: -35.0188, lng: 138.5684 },
  "Griffith University": { lat: -27.9625, lng: 153.3812 },
  "James Cook University": { lat: -19.3295, lng: 146.7567 },
  "La Trobe University": { lat: -37.7210, lng: 145.0490 },
  "Macquarie University": { lat: -33.7738, lng: 151.1126 },
  "Monash University": { lat: -37.9105, lng: 145.1362 },
  "Murdoch University": { lat: -32.0698, lng: 115.8394 },
  "Queensland University of Technology": { lat: -27.4771, lng: 153.0281 },
  "RMIT University": { lat: -37.8081, lng: 144.9631 },
  "Southern Cross University": { lat: -28.8150, lng: 153.2937 },
  "Swinburne University of Technology": { lat: -37.8222, lng: 145.0390 },
  "Torrens University Australia": { lat: -34.9224, lng: 138.5991 },
  "University of Adelaide": { lat: -34.9210, lng: 138.6041 },
  "University of Canberra": { lat: -35.2396, lng: 149.0845 },
  "University of Divinity": { lat: -37.7994, lng: 144.9651 },
  "University of Melbourne": { lat: -37.7983, lng: 144.9610 },
  "University of New England": { lat: -30.4888, lng: 151.6410 },
  "University of New South Wales": { lat: -33.9173, lng: 151.2313 },
  "University of Newcastle": { lat: -32.8915, lng: 151.6983 },
  "University of Notre Dame Australia": { lat: -33.4318, lng: 115.7636 },
  "University of Queensland": { lat: -27.4975, lng: 153.0137 },
  "University of South Australia": { lat: -34.8398, lng: 138.6271 },
  "University of Southern Queensland": { lat: -27.6220, lng: 151.9279 },
  "University of Sydney": { lat: -33.8886, lng: 151.1873 },
  "University of Tasmania": { lat: -42.9028, lng: 147.3254 },
  "University of Technology Sydney": { lat: -33.8832, lng: 151.2005 },
  "University of the Sunshine Coast": { lat: -26.7167, lng: 153.0667 },
  "University of Western Australia": { lat: -31.9793, lng: 115.8180 },
  "University of Wollongong": { lat: -34.4070, lng: 150.8785 },
  "Victoria University": { lat: -37.7936, lng: 144.8997 },
  "Western Sydney University": { lat: -33.7630, lng: 150.7505 },
};

export const australianStates = [
  { value: "NSW", label: "New South Wales" },
  { value: "VIC", label: "Victoria" },
  { value: "QLD", label: "Queensland" },
  { value: "WA", label: "Western Australia" },
  { value: "SA", label: "South Australia" },
  { value: "TAS", label: "Tasmania" },
  { value: "ACT", label: "Australian Capital Territory" },
  { value: "NT", label: "Northern Territory" },
];

export const universitySuburbs: Record<string, string[]> = {
  "University of New South Wales": ["Kensington", "Randwick", "Kingsford", "Maroubra", "Zetland"],
  "University of Sydney": ["Darlington", "Glebe", "Forest Lodge", "Newtown", "Redfern", "Surry Hills"],
  "University of Technology Sydney": ["Broadway", "Ultimo", "Haymarket", "Chippendale"],
  "University of Queensland": ["St Lucia", "Toowong", "Taringa", "Indooroopilly", "Dutton Park"],
  "Victoria University": ["Footscray", "Sunshine", "Maribyrnong", "St Albans"],
  "University of Adelaide": ["Adelaide CBD", "Mawson Lakes", "Magill", "Pooraka", "Salisbury"],
  "University of Western Australia": ["Crawley", "Nedlands", "Subiaco", "Shenton Park", "Daglish"],
  "Western Sydney University": ["Parramatta", "Penrith", "Kingswood", "Werrington", "Campbelltown"],
  "University of Newcastle": ["Jesmond", "Warabrook", "Birmingham Gardens", "Mayfield", "Wallsend"],
  "University of Wollongong": ["Wollongong", "North Wollongong", "Gwynneville", "Keiraville", "Mount Ousley"],
  "University of the Sunshine Coast": ["Buderim", "Sippy Downs", "Mountain Creek", "Mooloolaba"],
  "University of Tasmania": ["Sandy Bay", "Dynnyrne", "Mowbray", "Newnham", "Invermay"],
  "University of New England": ["Armidale CBD", "Guyra", "Uralla", "Kellys Plains"],
  "Monash University": ["Clayton", "Caulfield", "Notting Hill", "Wheelers Hill"],
  "RMIT University": ["Melbourne CBD", "Carlton", "Brunswick", "Bundoora"],
};
