export type CouncilWhatsOnLink = {
  slug: string;
  label: string;
  url: string;
};

const COUNCIL_WHATS_ON_LINKS_SOURCE: CouncilWhatsOnLink[] = [
  { slug: "albury-city-council", label: "Albury City Council", url: "https://www.alburycity.nsw.gov.au/whats-on" },
  { slug: "armidale-regional-council", label: "Armidale Regional Council", url: "https://www.armidaleregional.nsw.gov.au/events#ALL" },
  { slug: "ballina-shire-council", label: "Ballina Shire Council", url: "https://www.discoverballina.com.au/visit/whats-on/events-calendar/cat.listevents/" },
  { slug: "balranald-shire-council", label: "Balranald Shire Council", url: "https://balranald.nsw.gov.au/events/" },
  { slug: "bathurst-regional-council", label: "Bathurst Regional Council", url: "https://www.bathurst.nsw.gov.au/events.html" },
  { slug: "bayside-council", label: "Bayside Council", url: "https://www.bayside.nsw.gov.au/whats-on" },
  { slug: "bega-valley-shire-council", label: "Bega Valley Shire Council", url: "https://begavalley.nsw.gov.au/events-calendar/" },
  { slug: "bellingen-shire-council", label: "Bellingen Shire Council", url: "https://www.bellingen.nsw.gov.au/Events-directory" },
  { slug: "berrigan-shire-council", label: "Berrigan Shire Council", url: "https://www.berriganshire.nsw.gov.au/Events" },
  { slug: "blacktown-city-council", label: "Blacktown City Council", url: "https://www.blacktown.nsw.gov.au/Events-and-activities" },
  { slug: "bland-shire-council", label: "Bland Shire Council", url: "https://www.blandshire.nsw.gov.au/Community/Events-Directory" },
  { slug: "blayney-shire-council", label: "Blayney Shire Council", url: "https://www.blayney.nsw.gov.au/home/what-s-on" },
  { slug: "blue-mountains-city-council", label: "Blue Mountains City Council", url: "https://www.visitbluemountains.com.au/" },
  { slug: "bogan-shire-council", label: "Bogan Shire Council", url: "https://www.bogan.nsw.gov.au/tourism/events" },
  { slug: "bourke-shire-council", label: "Bourke Shire Council", url: "https://www.visitbourke.com.au/see-do/events-festivals" },
  { slug: "brewarrina-shire-council", label: "Brewarrina Shire Council", url: "https://visitbrewarrina.com.au/events-and-workshops/" },
  { slug: "broken-hill-city-council", label: "Broken Hill City Council", url: "https://www.brokenhill.nsw.gov.au/Community/Events-Calendar" },
  { slug: "burwood-council", label: "Burwood Council", url: "https://www.burwood.nsw.gov.au/For-Residents/Events-and-Activities/Events-directory" },
  { slug: "byron-shire-council", label: "Byron Shire Council", url: "https://www.byron.nsw.gov.au/Community/Events-and-venues/Whats-on-in-Byron-Shire" },
  { slug: "cabonne-council", label: "Cabonne Council", url: "https://www.cabonne.nsw.gov.au/Recreation/Events" },
  { slug: "camden-council", label: "Camden Council", url: "https://www.visitcamden.com.au/visit/" },
  { slug: "campbelltown-city-council", label: "Campbelltown City Council", url: "https://www.campbelltown.nsw.gov.au/Whats-On" },
  { slug: "canberra", label: "Canberra", url: "https://visitcanberra.com.au/events" },
  { slug: "canterbury-bankstown-council", label: "Canterbury-Bankstown Council", url: "https://whereinterestinghappens.com.au/" },
  { slug: "carrathool-shire-council", label: "Carrathool Shire Council", url: "https://carrathool.nsw.gov.au/events/" },
  { slug: "central-coast-council", label: "Central Coast Council", url: "https://www.centralcoast.nsw.gov.au/whats-on" },
  { slug: "central-darling-shire-council", label: "Central Darling Shire Council", url: "https://www.centraldarling.nsw.gov.au/Events-directory" },
  { slug: "cessnock-city-council", label: "Cessnock City Council", url: "https://www.cessnock.nsw.gov.au/Things-to-do/Events" },
  { slug: "city-of-canada-bay-council", label: "City of Canada Bay Council", url: "https://www.canadabay.nsw.gov.au/whats-on" },
  { slug: "city-of-lithgow-council", label: "City of Lithgow Council", url: "https://council.lithgow.com/events/" },
  { slug: "city-of-newcastle", label: "City of Newcastle", url: "https://whatson.newcastle.nsw.gov.au/events" },
  { slug: "city-of-ryde", label: "City of Ryde", url: "https://www.ryde.nsw.gov.au/Events/Listing" },
  { slug: "city-of-sydney", label: "City of Sydney", url: "https://whatson.cityofsydney.nsw.gov.au/events" },
  { slug: "clarence-valley-council", label: "Clarence Valley Council", url: "https://www.clarence.nsw.gov.au/Community/Events-directory" },
  { slug: "cobar-shire-council", label: "Cobar Shire Council", url: "https://visitcobarshire.com.au/events" },
  { slug: "coffs-harbour-city-council", label: "Coffs Harbour City Council", url: "https://www.coffsharbour.nsw.gov.au/Events-directory" },
  { slug: "coolamon-shire-council", label: "Coolamon Shire Council", url: "https://visitcoolamonshire.com.au/events" },
  { slug: "coonamble-shire-council", label: "Coonamble Shire Council", url: "https://coonambleshire.nsw.gov.au/events/events-calendar" },
  { slug: "cootamundra-gundagai-regional-council", label: "Cootamundra-Gundagai Regional Council", url: "https://www.cgrc.nsw.gov.au/whats-on/" },
  { slug: "cowra-shire-council", label: "Cowra Shire Council", url: "https://www.cowracouncil.com.au/Community/Events" },
  { slug: "cumberland-city-council", label: "Cumberland City Council", url: "https://www.cumberland.nsw.gov.au/whats-on" },
  { slug: "dubbo-regional-council", label: "Dubbo Regional Council", url: "https://dubbo.com.au/events/calendar" },
  { slug: "dungog-shire-council", label: "Dungog Shire Council", url: "https://www.dungog.nsw.gov.au/Community/Whats-on-in-Dungog" },
  { slug: "edward-river-council", label: "Edward River Council", url: "https://www.edwardriver.nsw.gov.au/Whats-On" },
  { slug: "eurobodalla-shire-council", label: "Eurobodalla Shire Council", url: "https://www.esc.nsw.gov.au/news-and-events/whats-on/events" },
  { slug: "fairfield-city-council", label: "Fairfield City Council", url: "https://www.discoverfairfield.com.au/Home" },
  { slug: "federation-council", label: "Federation Council", url: "https://www.federationcouncil.nsw.gov.au/Living-Here/Community-Events/Events-Activities" },
  { slug: "forbes-shire-council", label: "Forbes Shire Council", url: "https://www.forbes.nsw.gov.au/events" },
  { slug: "georges-river-council", label: "Georges River Council", url: "https://www.georgesriver.nsw.gov.au/Whats-On" },
  { slug: "gilgandra-shire-council", label: "Gilgandra Shire Council", url: "https://gilgandraregion.com.au/events" },
  { slug: "glen-innes-severn-council", label: "Glen Innes Severn Council", url: "https://www.gisc.nsw.gov.au/Events-Activities" },
  { slug: "goulburn-mulwaree-council", label: "Goulburn Mulwaree Council", url: "https://www.goulburn.nsw.gov.au/Community/Events" },
  { slug: "greater-hume-shire-council", label: "Greater Hume Shire Council", url: "https://www.greaterhume.nsw.gov.au/Events/Events-Calendar" },
  { slug: "gunnedah-shire-council", label: "Gunnedah Shire Council", url: "https://www.gunnedah.nsw.gov.au/index.php/gunnedah-shire-library/library-news/item/2023-latest-calendar-of-events-now-available" },
  { slug: "gwydir-shire-council", label: "Gwydir Shire Council", url: "https://www.gwydir.nsw.gov.au/Council/Events-Directory" },
  { slug: "hawkesbury-city-council", label: "Hawkesbury City Council", url: "https://www.discoverthehawkesbury.com.au/" },
  { slug: "hay-shire-council", label: "Hay Shire Council", url: "https://www.hay.nsw.gov.au/Home/PID/594/evl/0/CategoryID/3/CategoryName/Council-Events" },
  { slug: "hilltops-council", label: "Hilltops Council", url: "https://www.visithilltopsregion.com.au/" },
  { slug: "hornsby-shire-council", label: "Hornsby Shire Council", url: "https://www.hornsby.nsw.gov.au/lifestyle/events" },
  { slug: "hunters-hill-council", label: "Hunter's Hill Council", url: "https://www.huntershill.nsw.gov.au/events/" },
  { slug: "inner-west-council", label: "Inner West Council", url: "https://www.innerwest.nsw.gov.au/explore/whats-on#/" },
  { slug: "inverell-shire-council", label: "Inverell Shire Council", url: "https://inverell.nsw.gov.au/events/" },
  { slug: "junee-shire-council", label: "Junee Shire Council", url: "https://www.junee.nsw.gov.au/your-community/events/" },
  { slug: "kempsey-shire-council", label: "Kempsey Shire Council", url: "https://www.kempsey.nsw.gov.au/Your-Valley/Festivals-events/Events-directory" },
  { slug: "kiama-council", label: "Kiama Council", url: "https://www.kiama.nsw.gov.au/Events" },
  { slug: "ku-ring-gai-council", label: "Ku-ring-gai Council", url: "https://www.krg.nsw.gov.au/Things-to-do/Whats-on" },
  { slug: "kyogle-council", label: "Kyogle Council", url: "https://www.kyogle.nsw.gov.au/events/" },
  { slug: "lachlan-shire-council", label: "Lachlan Shire Council", url: "https://www.lachlan.nsw.gov.au/Events-directory" },
  { slug: "lake-macquarie-city-council", label: "Lake Macquarie City Council", url: "https://www.lakemac.com.au/Events-directory" },
  { slug: "lane-cove-council", label: "Lane Cove Council", url: "https://www.lanecove.nsw.gov.au/Events-directory" },
  { slug: "leeton-shire-council", label: "Leeton Shire Council", url: "https://www.leeton.nsw.gov.au/Discover-Leeton/Events" },
  { slug: "lismore-city-council", label: "Lismore City Council", url: "https://www.lismore.nsw.gov.au/Community/Events-venues/Whats-on" },
  { slug: "liverpool-city-council", label: "Liverpool City Council", url: "https://www.liverpool.nsw.gov.au/whats-on" },
  { slug: "liverpool-plains-shire-council", label: "Liverpool Plains Shire Council", url: "https://www.liverpoolplains.nsw.gov.au/Community/Events-directory" },
  { slug: "lockhart-shire-council", label: "Lockhart Shire Council", url: "https://www.visitlockhartshire.com.au/events/" },
  { slug: "maitland-city-council", label: "Maitland City Council", url: "https://www.maitlandevents.com.au/" },
  { slug: "mid-coast-council", label: "Mid-Coast Council", url: "https://www.midcoast.nsw.gov.au/Get-involved/Things-to-do/Whats-on" },
  { slug: "mid-western-regional-council", label: "Mid-Western Regional Council", url: "https://www.midwestern.nsw.gov.au/Community/Events-directory" },
  { slug: "moree-plains-shire-council", label: "Moree Plains Shire Council", url: "https://www.mpsc.nsw.gov.au/events" },
  { slug: "mosman-municipal-council", label: "Mosman Municipal Council", url: "https://events.mosman.nsw.gov.au/" },
  { slug: "murray-river-council", label: "Murray River Council", url: "https://www.murrayriver.nsw.gov.au/Events-directory" },
  { slug: "murrumbidgee-council", label: "Murrumbidgee Council", url: "https://www.murrumbidgee.nsw.gov.au/cp_themes/default/event-list.asp" },
  { slug: "muswellbrook-shire-council", label: "Muswellbrook Shire Council", url: "https://www.murrumbidgee.nsw.gov.au/cp_themes/default/event-list.asp" },
  { slug: "nambucca-valley-council", label: "Nambucca Valley Council", url: "https://www.nambucca.nsw.gov.au/Events-directory" },
  { slug: "narrabri-shire-council", label: "Narrabri Shire Council", url: "https://www.narrabri.nsw.gov.au/Events-directory" },
  { slug: "narrandera-shire-council", label: "Narrandera Shire Council", url: "https://www.narrandera.nsw.gov.au/events" },
  { slug: "narromine-shire-council", label: "Narromine Shire Council", url: "https://narromineregion.com.au/calendar" },
  { slug: "north-sydney-council", label: "North Sydney Council", url: "https://www.northsydney.nsw.gov.au/events" },
  { slug: "northern-beaches-council", label: "Northern Beaches Council", url: "https://www.northernbeaches.nsw.gov.au/things-to-do/whats-on/event-calendar" },
  { slug: "oberon-council", label: "Oberon Council", url: "https://www.oberon.nsw.gov.au/Community/Events-directory" },
  { slug: "orange-city-council", label: "Orange City Council", url: "https://www.orange.nsw.gov.au/events/" },
  { slug: "parkes-shire-council", label: "Parkes Shire Council", url: "https://www.parkes.nsw.gov.au/Community/Events-and-festivals" },
  { slug: "parramatta-city-council", label: "Parramatta City Council", url: "https://atparramatta.com/whats-on/calendar" },
  { slug: "penrith-city-council", label: "Penrith City Council", url: "https://www.visitpenrith.com.au/events" },
  { slug: "port-macquarie-hastings-council", label: "Port Macquarie-Hastings Council", url: "https://www.pmhc.nsw.gov.au/Places/Events/Events-calendar" },
  { slug: "port-stephens-council", label: "Port Stephens Council", url: "https://www.portstephens.nsw.gov.au/community/events" },
  { slug: "queanbeyan-palerang-regional-council", label: "Queanbeyan-Palerang Regional Council", url: "https://www.qprc.nsw.gov.au/Events" },
  { slug: "randwick-city-council", label: "Randwick City Council", url: "https://www.randwick.nsw.gov.au/community/whats-on" },
  { slug: "richmond-valley-council", label: "Richmond Valley Council", url: "https://richmondvalley.nsw.gov.au/community-services/events-in-the-valley/" },
  { slug: "shellharbour-city-council", label: "Shellharbour City Council", url: "https://www.shellharbour.nsw.gov.au/whats-on" },
  { slug: "shoalhaven-city-council", label: "Shoalhaven City Council", url: "https://www.shoalhaven.nsw.gov.au/Council/Events-Awards" },
  { slug: "singleton-council", label: "Singleton Council", url: "https://www.singleton.nsw.gov.au/Experience/Events/Whats-On" },
  { slug: "snowy-monaro-regional-council", label: "Snowy Monaro Regional Council", url: "https://www.snowymonaro.nsw.gov.au/Events-directory" },
  { slug: "snowy-valleys-council", label: "Snowy Valleys Council", url: "https://visitsnowyvalleys.au/experience/event/" },
  { slug: "strathfield-municipal-council", label: "Strathfield Municipal Council", url: "https://www.strathfield.nsw.gov.au/play/events/" },
  { slug: "sutherland-shire-council", label: "Sutherland Shire Council", url: "https://www.sutherlandshire.nsw.gov.au/events" },
  { slug: "tamworth-regional-council", label: "Tamworth Regional Council", url: "https://www.tamworth.nsw.gov.au/EventSearch/WhatsOnEvents.aspx" },
  { slug: "temora-shire-council", label: "Temora Shire Council", url: "https://temora.com.au/events" },
  { slug: "the-hills-shire-council", label: "The Hills Shire Council", url: "https://www.thehills.nsw.gov.au/Upcoming-Events-Activities" },
  { slug: "tweed-shire-council", label: "Tweed Shire Council", url: "https://whatsontweed.com.au/" },
  { slug: "upper-hunter-shire-council", label: "Upper Hunter Shire Council", url: "https://www.upperhunter.nsw.gov.au/Events-Activities" },
  { slug: "upper-lachlan-shire-council", label: "Upper Lachlan Shire Council", url: "https://www.visitupperlachlan.com.au/see-do/all-events/" },
  { slug: "uralla-shire-council", label: "Uralla Shire Council", url: "https://www.uralla.nsw.gov.au/Community/Community-Events" },
  { slug: "wagga-wagga-city-council", label: "Wagga Wagga City Council", url: "https://visitwagga.com/calendar" },
  { slug: "walcha-council", label: "Walcha Council", url: "https://walchansw.com.au/whats-on/" },
  { slug: "walgett-shire-council", label: "Walgett Shire Council", url: "https://www.walgett.nsw.gov.au/Events-Activities" },
  { slug: "warren-shire-council", label: "Warren Shire Council", url: "https://www.warren.nsw.gov.au/discover/events-calendar" },
  { slug: "warrumbungle-shire-council", label: "Warrumbungle Shire Council", url: "https://www.warrumbungle.nsw.gov.au/tourism/events/event-calendar" },
  { slug: "waverley-council", label: "Waverley Council", url: "https://www.waverley.nsw.gov.au/recreation/events" },
  { slug: "weddin-shire-council", label: "Weddin Shire Council", url: "https://visitweddin.com.au/events/" },
  { slug: "wentworth-shire-council", label: "Wentworth Shire Council", url: "https://experiencewentworth.com.au/EventPages.aspx" },
  { slug: "willoughby-city-council", label: "Willoughby City Council", url: "https://www.willoughby.nsw.gov.au/Events" },
  { slug: "wingecarribee-shire-council", label: "Wingecarribee Shire Council", url: "https://www.wsc.nsw.gov.au/events-directory" },
  { slug: "wollondilly-shire-council", label: "Wollondilly Shire Council", url: "https://www.visitwollondilly.com.au/" },
  { slug: "wollongong-city-council", label: "Wollongong City Council", url: "https://www.wollongong.nsw.gov.au/whats-on/events" },
  { slug: "woollahra-municipal-council", label: "Woollahra Municipal Council", url: "https://www.woollahra.nsw.gov.au/events" },
  { slug: "yass-valley-council", label: "Yass Valley Council", url: "https://www.yassvalley.nsw.gov.au/Our-Community/Community-Events" },
];

const DEFAULT_COUNCIL_WHATS_ON_SLUG = "city-of-sydney";

export const COUNCIL_WHATS_ON_LINKS = [...COUNCIL_WHATS_ON_LINKS_SOURCE].sort(
  (left, right) => {
    if (left.slug === DEFAULT_COUNCIL_WHATS_ON_SLUG) return -1;
    if (right.slug === DEFAULT_COUNCIL_WHATS_ON_SLUG) return 1;
    return left.label.localeCompare(right.label);
  },
);

export function getCouncilWhatsOnLink(slug: string) {
  const normalizedSlug = String(slug || "").trim();
  if (!normalizedSlug) return null;
  return (
    COUNCIL_WHATS_ON_LINKS.find((link) => link.slug === normalizedSlug) || null
  );
}
