// Compact list of all countries
export const allCountries: { label: string; value: string }[] = [
  { label: "Afghanistan", value: "AF" },
  { label: "Albania", value: "AL" },
  { label: "Algeria", value: "DZ" },
  { label: "Andorra", value: "AD" },
  { label: "Angola", value: "AO" },
  { label: "Antigua and Barbuda", value: "AG" },
  { label: "Argentina", value: "AR" },
  { label: "Armenia", value: "AM" },
  { label: "Australia", value: "AU" },
  { label: "Austria", value: "AT" },
  { label: "Azerbaijan", value: "AZ" },
  { label: "Bahamas", value: "BS" },
  { label: "Bahrain", value: "BH" },
  { label: "Bangladesh", value: "BD" },
  { label: "Barbados", value: "BB" },
  { label: "Belarus", value: "BY" },
  { label: "Belgium", value: "BE" },
  { label: "Belize", value: "BZ" },
  { label: "Benin", value: "BJ" },
  { label: "Bhutan", value: "BT" },
  { label: "Bolivia", value: "BO" },
  { label: "Bosnia and Herzegovina", value: "BA" },
  { label: "Botswana", value: "BW" },
  { label: "Brazil", value: "BR" },
  { label: "Brunei", value: "BN" },
  { label: "Bulgaria", value: "BG" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Burundi", value: "BI" },
  { label: "Cambodia", value: "KH" },
  { label: "Cameroon", value: "CM" },
  { label: "Canada", value: "CA" },
  { label: "Cape Verde", value: "CV" },
  { label: "Central African Republic", value: "CF" },
  { label: "Chad", value: "TD" },
  { label: "Chile", value: "CL" },
  { label: "China", value: "CN" },
  { label: "Colombia", value: "CO" },
  { label: "Comoros", value: "KM" },
  { label: "Congo (DRC)", value: "CD" },
  { label: "Congo (Republic)", value: "CG" },
  { label: "Costa Rica", value: "CR" },
  { label: "Croatia", value: "HR" },
  { label: "Cuba", value: "CU" },
  { label: "Cyprus", value: "CY" },
  { label: "Czech Republic", value: "CZ" },
  { label: "Denmark", value: "DK" },
  { label: "Djibouti", value: "DJ" },
  { label: "Dominica", value: "DM" },
  { label: "Dominican Republic", value: "DO" },
  { label: "East Timor", value: "TL" },
  { label: "Ecuador", value: "EC" },
  { label: "Egypt", value: "EG" },
  { label: "El Salvador", value: "SV" },
  { label: "Equatorial Guinea", value: "GQ" },
  { label: "Eritrea", value: "ER" },
  { label: "Estonia", value: "EE" },
  { label: "Eswatini", value: "SZ" },
  { label: "Ethiopia", value: "ET" },
  { label: "Fiji", value: "FJ" },
  { label: "Finland", value: "FI" },
  { label: "France", value: "FR" },
  { label: "Gabon", value: "GA" },
  { label: "Gambia", value: "GM" },
  { label: "Georgia", value: "GE" },
  { label: "Germany", value: "DE" },
  { label: "Ghana", value: "GH" },
  { label: "Greece", value: "GR" },
  { label: "Grenada", value: "GD" },
  { label: "Guatemala", value: "GT" },
  { label: "Guinea", value: "GN" },
  { label: "Guinea-Bissau", value: "GW" },
  { label: "Guyana", value: "GY" },
  { label: "Haiti", value: "HT" },
  { label: "Honduras", value: "HN" },
  { label: "Hungary", value: "HU" },
  { label: "Iceland", value: "IS" },
  { label: "India", value: "IN" },
  { label: "Indonesia", value: "ID" },
  { label: "Iran", value: "IR" },
  { label: "Iraq", value: "IQ" },
  { label: "Ireland", value: "IE" },
  { label: "Israel", value: "IL" },
  { label: "Italy", value: "IT" },
  { label: "Ivory Coast", value: "CI" },
  { label: "Jamaica", value: "JM" },
  { label: "Japan", value: "JP" },
  { label: "Jordan", value: "JO" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Kenya", value: "KE" },
  { label: "Kiribati", value: "KI" },
  { label: "Kosovo", value: "XK" },
  { label: "Kuwait", value: "KW" },
  { label: "Kyrgyzstan", value: "KG" },
  { label: "Laos", value: "LA" },
  { label: "Latvia", value: "LV" },
  { label: "Lebanon", value: "LB" },
  { label: "Lesotho", value: "LS" },
  { label: "Liberia", value: "LR" },
  { label: "Libya", value: "LY" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Lithuania", value: "LT" },
  { label: "Luxembourg", value: "LU" },
  { label: "Madagascar", value: "MG" },
  { label: "Malawi", value: "MW" },
  { label: "Malaysia", value: "MY" },
  { label: "Maldives", value: "MV" },
  { label: "Mali", value: "ML" },
  { label: "Malta", value: "MT" },
  { label: "Marshall Islands", value: "MH" },
  { label: "Mauritania", value: "MR" },
  { label: "Mauritius", value: "MU" },
  { label: "Mexico", value: "MX" },
  { label: "Micronesia", value: "FM" },
  { label: "Moldova", value: "MD" },
  { label: "Monaco", value: "MC" },
  { label: "Mongolia", value: "MN" },
  { label: "Montenegro", value: "ME" },
  { label: "Morocco", value: "MA" },
  { label: "Mozambique", value: "MZ" },
  { label: "Myanmar", value: "MM" },
  { label: "Namibia", value: "NA" },
  { label: "Nauru", value: "NR" },
  { label: "Nepal", value: "NP" },
  { label: "Netherlands", value: "NL" },
  { label: "New Zealand", value: "NZ" },
  { label: "Nicaragua", value: "NI" },
  { label: "Niger", value: "NE" },
  { label: "Nigeria", value: "NG" },
  { label: "North Korea", value: "KP" },
  { label: "North Macedonia", value: "MK" },
  { label: "Norway", value: "NO" },
  { label: "Oman", value: "OM" },
  { label: "Pakistan", value: "PK" },
  { label: "Palau", value: "PW" },
  { label: "Palestine", value: "PS" },
  { label: "Panama", value: "PA" },
  { label: "Papua New Guinea", value: "PG" },
  { label: "Paraguay", value: "PY" },
  { label: "Peru", value: "PE" },
  { label: "Philippines", value: "PH" },
  { label: "Poland", value: "PL" },
  { label: "Portugal", value: "PT" },
  { label: "Qatar", value: "QA" },
  { label: "Romania", value: "RO" },
  { label: "Russia", value: "RU" },
  { label: "Rwanda", value: "RW" },
  { label: "Saint Kitts and Nevis", value: "KN" },
  { label: "Saint Lucia", value: "LC" },
  { label: "Saint Vincent and the Grenadines", value: "VC" },
  { label: "Samoa", value: "WS" },
  { label: "San Marino", value: "SM" },
  { label: "Sao Tome and Principe", value: "ST" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Senegal", value: "SN" },
  { label: "Serbia", value: "RS" },
  { label: "Seychelles", value: "SC" },
  { label: "Sierra Leone", value: "SL" },
  { label: "Singapore", value: "SG" },
  { label: "Slovakia", value: "SK" },
  { label: "Slovenia", value: "SI" },
  { label: "Solomon Islands", value: "SB" },
  { label: "Somalia", value: "SO" },
  { label: "South Africa", value: "ZA" },
  { label: "South Korea", value: "KR" },
  { label: "South Sudan", value: "SS" },
  { label: "Spain", value: "ES" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Sudan", value: "SD" },
  { label: "Suriname", value: "SR" },
  { label: "Sweden", value: "SE" },
  { label: "Switzerland", value: "CH" },
  { label: "Syria", value: "SY" },
  { label: "Taiwan", value: "TW" },
  { label: "Tajikistan", value: "TJ" },
  { label: "Tanzania", value: "TZ" },
  { label: "Thailand", value: "TH" },
  { label: "Togo", value: "TG" },
  { label: "Tonga", value: "TO" },
  { label: "Trinidad and Tobago", value: "TT" },
  { label: "Tunisia", value: "TN" },
  { label: "Turkey", value: "TR" },
  { label: "Turkmenistan", value: "TM" },
  { label: "Tuvalu", value: "TV" },
  { label: "Uganda", value: "UG" },
  { label: "Ukraine", value: "UA" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "United Kingdom", value: "GB" },
  { label: "United States", value: "US" },
  { label: "Uruguay", value: "UY" },
  { label: "Uzbekistan", value: "UZ" },
  { label: "Vanuatu", value: "VU" },
  { label: "Vatican City", value: "VA" },
  { label: "Venezuela", value: "VE" },
  { label: "Vietnam", value: "VN" },
  { label: "Yemen", value: "YE" },
  { label: "Zambia", value: "ZM" },
  { label: "Zimbabwe", value: "ZW" },
];

// States/provinces by country code (primary markets)
export const statesByCountry: Record<string, { label: string; value: string }[]> = {
  IN: [
    { label: "Andhra Pradesh", value: "AP" },
    { label: "Arunachal Pradesh", value: "AR" },
    { label: "Assam", value: "AS" },
    { label: "Bihar", value: "BR" },
    { label: "Chhattisgarh", value: "CT" },
    { label: "Goa", value: "GA" },
    { label: "Gujarat", value: "GJ" },
    { label: "Haryana", value: "HR" },
    { label: "Himachal Pradesh", value: "HP" },
    { label: "Jharkhand", value: "JH" },
    { label: "Karnataka", value: "KA" },
    { label: "Kerala", value: "KL" },
    { label: "Madhya Pradesh", value: "MP" },
    { label: "Maharashtra", value: "MH" },
    { label: "Manipur", value: "MN" },
    { label: "Meghalaya", value: "ML" },
    { label: "Mizoram", value: "MZ" },
    { label: "Nagaland", value: "NL" },
    { label: "Odisha", value: "OR" },
    { label: "Punjab", value: "PB" },
    { label: "Rajasthan", value: "RJ" },
    { label: "Sikkim", value: "SK" },
    { label: "Tamil Nadu", value: "TN" },
    { label: "Telangana", value: "TG" },
    { label: "Tripura", value: "TR" },
    { label: "Uttar Pradesh", value: "UP" },
    { label: "Uttarakhand", value: "UK" },
    { label: "West Bengal", value: "WB" },
    { label: "Andaman and Nicobar Islands", value: "AN" },
    { label: "Chandigarh", value: "CH" },
    { label: "Dadra and Nagar Haveli and Daman and Diu", value: "DH" },
    { label: "Delhi", value: "DL" },
    { label: "Jammu and Kashmir", value: "JK" },
    { label: "Ladakh", value: "LA" },
    { label: "Lakshadweep", value: "LD" },
    { label: "Puducherry", value: "PY" },
  ],
  PK: [
    { label: "Balochistan", value: "BA" },
    { label: "Islamabad Capital Territory", value: "IS" },
    { label: "Khyber Pakhtunkhwa", value: "KP" },
    { label: "Punjab", value: "PB" },
    { label: "Sindh", value: "SD" },
    { label: "Azad Jammu and Kashmir", value: "JK" },
    { label: "Gilgit-Baltistan", value: "GB" },
  ],
  BD: [
    { label: "Barishal", value: "A" },
    { label: "Chattogram", value: "B" },
    { label: "Dhaka", value: "C" },
    { label: "Khulna", value: "D" },
    { label: "Mymensingh", value: "H" },
    { label: "Rajshahi", value: "E" },
    { label: "Rangpur", value: "F" },
    { label: "Sylhet", value: "G" },
  ],
  LK: [
    { label: "Central Province", value: "CP" },
    { label: "Eastern Province", value: "EP" },
    { label: "North Central Province", value: "NCP" },
    { label: "Northern Province", value: "NP" },
    { label: "North Western Province", value: "NWP" },
    { label: "Sabaragamuwa Province", value: "SP" },
    { label: "Southern Province", value: "SOP" },
    { label: "Uva Province", value: "UP" },
    { label: "Western Province", value: "WP" },
  ],
  NP: [
    { label: "Province No. 1 (Koshi)", value: "1" },
    { label: "Province No. 2 (Madhesh)", value: "2" },
    { label: "Bagmati Province", value: "3" },
    { label: "Gandaki Province", value: "4" },
    { label: "Lumbini Province", value: "5" },
    { label: "Karnali Province", value: "6" },
    { label: "Sudurpashchim Province", value: "7" },
  ],
  CN: [
    { label: "Anhui", value: "AH" },
    { label: "Beijing", value: "BJ" },
    { label: "Chongqing", value: "CQ" },
    { label: "Fujian", value: "FJ" },
    { label: "Gansu", value: "GS" },
    { label: "Guangdong", value: "GD" },
    { label: "Guangxi", value: "GX" },
    { label: "Guizhou", value: "GZ" },
    { label: "Hainan", value: "HI" },
    { label: "Hebei", value: "HE" },
    { label: "Heilongjiang", value: "HL" },
    { label: "Henan", value: "HA" },
    { label: "Hubei", value: "HB" },
    { label: "Hunan", value: "HN" },
    { label: "Inner Mongolia", value: "NM" },
    { label: "Jiangsu", value: "JS" },
    { label: "Jiangxi", value: "JX" },
    { label: "Jilin", value: "JL" },
    { label: "Liaoning", value: "LN" },
    { label: "Ningxia", value: "NX" },
    { label: "Qinghai", value: "QH" },
    { label: "Shaanxi", value: "SN" },
    { label: "Shandong", value: "SD" },
    { label: "Shanghai", value: "SH" },
    { label: "Shanxi", value: "SX" },
    { label: "Sichuan", value: "SC" },
    { label: "Tianjin", value: "TJ" },
    { label: "Tibet", value: "XZ" },
    { label: "Xinjiang", value: "XJ" },
    { label: "Yunnan", value: "YN" },
    { label: "Zhejiang", value: "ZJ" },
  ],
  VN: [
    { label: "An Giang", value: "AG" },
    { label: "Ba Ria-Vung Tau", value: "BR" },
    { label: "Binh Duong", value: "BD" },
    { label: "Can Tho", value: "CT" },
    { label: "Da Nang", value: "DN" },
    { label: "Ha Noi", value: "HN" },
    { label: "Ho Chi Minh City", value: "HC" },
    { label: "Khanh Hoa", value: "KH" },
    { label: "Thua Thien Hue", value: "TH" },
  ],
  PH: [
    { label: "Metro Manila (NCR)", value: "NCR" },
    { label: "Cordillera Administrative Region", value: "CAR" },
    { label: "Ilocos Region", value: "01" },
    { label: "Cagayan Valley", value: "02" },
    { label: "Central Luzon", value: "03" },
    { label: "CALABARZON", value: "4A" },
    { label: "MIMAROPA", value: "4B" },
    { label: "Bicol Region", value: "05" },
    { label: "Western Visayas", value: "06" },
    { label: "Central Visayas", value: "07" },
    { label: "Eastern Visayas", value: "08" },
    { label: "Zamboanga Peninsula", value: "09" },
    { label: "Northern Mindanao", value: "10" },
    { label: "Davao Region", value: "11" },
    { label: "SOCCSKSARGEN", value: "12" },
    { label: "Caraga", value: "13" },
    { label: "BARMM", value: "BARMM" },
  ],
};

export function getStatesForCountry(countryCode: string): { label: string; value: string }[] {
  return statesByCountry[countryCode] || [];
}

export function getCountryName(code: string): string {
  return allCountries.find(c => c.value === code)?.label || '';
}

export const airportData = {
  type: 'FeatureCollection',
  features: [
    { type: 'Feature', geometry: { type: 'Point', coordinates: [151.1772, -33.9461] }, properties: { name: 'Sydney Airport', iata: 'SYD', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [144.8430, -37.6690] }, properties: { name: 'Melbourne Airport', iata: 'MEL', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [153.1175, -27.3842] }, properties: { name: 'Brisbane Airport', iata: 'BNE', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [115.9669, -31.9403] }, properties: { name: 'Perth Airport', iata: 'PER', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [138.5306, -34.9450] }, properties: { name: 'Adelaide Airport', iata: 'ADL', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [149.1950, -35.3069] }, properties: { name: 'Canberra Airport', iata: 'CBR', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [147.5099, -42.8361] }, properties: { name: 'Hobart Airport', iata: 'HBA', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [130.8775, -12.4147] }, properties: { name: 'Darwin Airport', iata: 'DRW', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [153.5053, -28.1644] }, properties: { name: 'Gold Coast Airport', iata: 'OOL', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [151.8330, -32.7949] }, properties: { name: 'Newcastle Airport', iata: 'NTL', type: 'Domestic' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [153.0911, -26.6033] }, properties: { name: 'Sunshine Coast Airport', iata: 'MCY', type: 'Domestic' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [145.7553, -16.8858] }, properties: { name: 'Cairns Airport', iata: 'CNS', type: 'International' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [146.7649, -19.2525] }, properties: { name: 'Townsville Airport', iata: 'TSV', type: 'Domestic' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [147.2142, -41.5453] }, properties: { name: 'Launceston Airport', iata: 'LST', type: 'Domestic' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [144.4694, -38.0264] }, properties: { name: 'Avalon Airport', iata: 'AVV', type: 'International' } },
  ],
} as const;
